id: A4F684DB4
base_file: f97AC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:09:05.399006
  last_modified_at: 2022-05-30 23:09:05.399011
